name: resync_xdf
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=4.0.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.13.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - bleach=6.1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.1.4
  - contourpy=1.1.1
  - cycler=0.12.1
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - edflib-python=1.0.8
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - exceptiongroup=1.1.3
  - executing=2.0.1
  - fonttools=4.44.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - future=0.18.3
  - gettext=0.21.1
  - glib=2.78.0
  - glib-tools=2.78.0
  - gst-plugins-base=1.22.6
  - gstreamer=1.22.6
  - h5py=3.10.0
  - hdf5=1.14.2
  - icu=73.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.1.0
  - intel-openmp=2023.2.0
  - ipykernel=6.26.0
  - ipython=8.17.2
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.1
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.2
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.19.2
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.5.0
  - jupyter_console=6.6.3
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.9.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.8
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.25.0
  - jupyterlab_widgets=3.0.9
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.15
  - lerc=4.0.0
  - libaec=1.1.2
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcurl=8.4.0
  - libdeflate=1.19
  - libexpat=2.5.0
  - libffi=3.4.2
  - libglib=2.78.0
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libogg=1.3.4
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.44.0
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.11.5
  - libzlib=1.2.13
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.3
  - matplotlib=3.8.1
  - matplotlib-base=3.8.1
  - matplotlib-inline=0.1.6
  - mistune=3.0.2
  - mkl=2023.2.0
  - mne-base=1.5.1
  - mne-bids=0.13
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbconvert-core=7.10.0
  - nbconvert-pandoc=7.10.0
  - nbformat=5.9.2
  - nest-asyncio=1.5.8
  - nibabel=5.1.0
  - notebook=7.0.6
  - notebook-shim=0.2.3
  - numpy=1.26.0
  - openjpeg=2.5.0
  - openpyxl=3.1.2
  - openssl=3.2.0
  - overrides=7.4.0
  - packaging=23.2
  - pandas=2.1.2
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.40
  - pickleshare=0.7.5
  - pillow=10.1.0
  - pip=23.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.11.0
  - ply=3.11
  - pooch=1.8.0
  - prometheus_client=0.18.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - pybv=0.7.5
  - pycparser=2.21
  - pygments=2.16.1
  - pymatreader=0.0.32
  - pyparsing=3.1.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.12.0
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytz=2023.3.post1
  - pywin32=306
  - pywinpty=2.0.12
  - pyxdf=1.16.4
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - qt-main=5.15.8
  - qtconsole-base=5.4.4
  - qtpy=2.4.1
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - scipy=1.11.3
  - send2trash=1.8.2
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - stack_data=0.6.2
  - tbb=2021.10.0
  - terminado=0.17.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.13.0
  - types-python-dateutil=2.8.19.14
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - typing_utils=0.1.0
  - tzdata=2023c
  - ucrt=10.0.22621.0
  - uri-template=1.3.0
  - urllib3=2.0.7
  - vc=14.3
  - vc14_runtime=14.36.32532
  - vs2015_runtime=14.36.32532
  - wcwidth=0.2.9
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.6.4
  - wheel=0.41.3
  - widgetsnbextension=4.0.9
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xmltodict=0.13.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zstd=1.5.5
  - pip:
      - black==24.3.0
      - click==8.1.7
      - mypy-extensions==1.0.0
      - pathspec==0.12.1
      - pte-xdf==0.1.0
      - pyedflib==0.1.36
      - xdf4mne==0.0.4
      - mnelab==0.9.1
      - pyxdf==1.16.6
      - shiboken6==6.6.3.1
      - pyside6==6.6.3.1
      - pyside6-addons==6.6.3.1
      - pyside6-essentials==6.6.3.1

